[package]
name = "transrust"
version = "0.1.0"
authors = ["Gauvain Devillez <gauvain.devillez@umons.ac.be>"]

[dependencies]

rayon = "1.0"
graph = {git = "https://github.com/umons-dept-comp-sci/PhoegRustGraph.git", branch="discov-test"}
time = "0.1"
docopt = "0.8"
serde="1.0"
serde_derive="1.0"
rustc-serialize = "0.3"
