.include "definitions.dl"

Transformation("AddVertexLabel").

ConcreteOperation($AddVertexLabel(vertex, label)):-
    TargetVertex(vertex),
    TargetVertexLabel(label),
    !VertexHasLabel(vertex, label).

ConcreteOperation($AddVertex(vertex)):-
    !Vertex(vertex),
    TargetVertex(vertex).

Next($AddVertex(vertex), $AddVertex(vertex), $AddVertexLabel(vertex, label)):-
    ConcreteOperation($AddVertex(vertex)),
    ConcreteOperation($AddVertexLabel(vertex, label)).
